// flow-typed signature: 484e09115e490cdc159e846aeb386244
// flow-typed version: <<STUB>>/botfuel-qna-sdk_v^1.1.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'botfuel-qna-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'botfuel-qna-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'botfuel-qna-sdk/build/api/api-resource' {
  declare module.exports: any;
}

declare module 'botfuel-qna-sdk/build/api/v0/index' {
  declare module.exports: any;
}

declare module 'botfuel-qna-sdk/build/api/v1/index' {
  declare module.exports: any;
}

declare module 'botfuel-qna-sdk/build/config' {
  declare module.exports: any;
}

declare module 'botfuel-qna-sdk/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'botfuel-qna-sdk/build/api/api-resource.js' {
  declare module.exports: $Exports<'botfuel-qna-sdk/build/api/api-resource'>;
}
declare module 'botfuel-qna-sdk/build/api/v0/index.js' {
  declare module.exports: $Exports<'botfuel-qna-sdk/build/api/v0/index'>;
}
declare module 'botfuel-qna-sdk/build/api/v1/index.js' {
  declare module.exports: $Exports<'botfuel-qna-sdk/build/api/v1/index'>;
}
declare module 'botfuel-qna-sdk/build/config.js' {
  declare module.exports: $Exports<'botfuel-qna-sdk/build/config'>;
}
declare module 'botfuel-qna-sdk/build/index.js' {
  declare module.exports: $Exports<'botfuel-qna-sdk/build/index'>;
}
declare module 'botfuel-qna-sdk/index' {
  declare module.exports: $Exports<'botfuel-qna-sdk'>;
}
declare module 'botfuel-qna-sdk/index.js' {
  declare module.exports: $Exports<'botfuel-qna-sdk'>;
}
