// flow-typed signature: 12f59faea9fb1f5a7f853ee6510dda04
// flow-typed version: <<STUB>>/botfuel-nlp-sdk_v^1.1.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'botfuel-nlp-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'botfuel-nlp-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'botfuel-nlp-sdk/build/config' {
  declare module.exports: any;
}

declare module 'botfuel-nlp-sdk/build/index' {
  declare module.exports: any;
}

declare module 'botfuel-nlp-sdk/build/resources/api-resource' {
  declare module.exports: any;
}

declare module 'botfuel-nlp-sdk/build/resources/entity-extraction' {
  declare module.exports: any;
}

declare module 'botfuel-nlp-sdk/build/resources/sentiment-analysis' {
  declare module.exports: any;
}

declare module 'botfuel-nlp-sdk/build/resources/spellchecking' {
  declare module.exports: any;
}

// Filename aliases
declare module 'botfuel-nlp-sdk/build/config.js' {
  declare module.exports: $Exports<'botfuel-nlp-sdk/build/config'>;
}
declare module 'botfuel-nlp-sdk/build/index.js' {
  declare module.exports: $Exports<'botfuel-nlp-sdk/build/index'>;
}
declare module 'botfuel-nlp-sdk/build/resources/api-resource.js' {
  declare module.exports: $Exports<'botfuel-nlp-sdk/build/resources/api-resource'>;
}
declare module 'botfuel-nlp-sdk/build/resources/entity-extraction.js' {
  declare module.exports: $Exports<'botfuel-nlp-sdk/build/resources/entity-extraction'>;
}
declare module 'botfuel-nlp-sdk/build/resources/sentiment-analysis.js' {
  declare module.exports: $Exports<'botfuel-nlp-sdk/build/resources/sentiment-analysis'>;
}
declare module 'botfuel-nlp-sdk/build/resources/spellchecking.js' {
  declare module.exports: $Exports<'botfuel-nlp-sdk/build/resources/spellchecking'>;
}
declare module 'botfuel-nlp-sdk/index' {
  declare module.exports: $Exports<'botfuel-nlp-sdk'>;
}
declare module 'botfuel-nlp-sdk/index.js' {
  declare module.exports: $Exports<'botfuel-nlp-sdk'>;
}
