// flow-typed signature: e9abfefeb461180402386e1b014c901b
// flow-typed version: <<STUB>>/diacritics_v^1.3.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'diacritics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'diacritics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'diacritics/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'diacritics/index' {
  declare module.exports: $Exports<'diacritics'>;
}
declare module 'diacritics/index.js' {
  declare module.exports: $Exports<'diacritics'>;
}
declare module 'diacritics/test/test.js' {
  declare module.exports: $Exports<'diacritics/test/test'>;
}
