// flow-typed signature: 5423a5f6c553df119d9b06b5f50640e3
// flow-typed version: <<STUB>>/express-handlebars_v^3.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-handlebars'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-handlebars' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-handlebars/lib/express-handlebars' {
  declare module.exports: any;
}

declare module 'express-handlebars/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-handlebars/index' {
  declare module.exports: $Exports<'express-handlebars'>;
}
declare module 'express-handlebars/index.js' {
  declare module.exports: $Exports<'express-handlebars'>;
}
declare module 'express-handlebars/lib/express-handlebars.js' {
  declare module.exports: $Exports<'express-handlebars/lib/express-handlebars'>;
}
declare module 'express-handlebars/lib/utils.js' {
  declare module.exports: $Exports<'express-handlebars/lib/utils'>;
}
