// flow-typed signature: 38019735b61ad971ad6b1e1ea6b5e550
// flow-typed version: <<STUB>>/fs_v0.0.1-security

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fs' {
  declare module.exports: any;
}
