// flow-typed signature: f676597c4a5dbac99b2f661eae1d36b5
// flow-typed version: <<STUB>>/logtown_v2.1.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'logtown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'logtown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'logtown/es5/common/index' {
  declare module.exports: any;
}

declare module 'logtown/es5/common/plugins/stacktrace' {
  declare module.exports: any;
}

declare module 'logtown/es5/umd/index' {
  declare module.exports: any;
}

declare module 'logtown/es5/umd/plugins/stacktrace' {
  declare module.exports: any;
}

declare module 'logtown/es6/common/index' {
  declare module.exports: any;
}

declare module 'logtown/es6/common/plugins/stacktrace' {
  declare module.exports: any;
}

declare module 'logtown/plugins/stacktrace' {
  declare module.exports: any;
}

declare module 'logtown/rollup.config.browser.es5' {
  declare module.exports: any;
}

declare module 'logtown/rollup.config.cjs.es5' {
  declare module.exports: any;
}

declare module 'logtown/rollup.config.cjs.es6' {
  declare module.exports: any;
}

declare module 'logtown/utils/color' {
  declare module.exports: any;
}

declare module 'logtown/wrappers/console' {
  declare module.exports: any;
}

declare module 'logtown/wrappers/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'logtown/es5/common/index.js' {
  declare module.exports: $Exports<'logtown/es5/common/index'>;
}
declare module 'logtown/es5/common/plugins/stacktrace.js' {
  declare module.exports: $Exports<'logtown/es5/common/plugins/stacktrace'>;
}
declare module 'logtown/es5/umd/index.js' {
  declare module.exports: $Exports<'logtown/es5/umd/index'>;
}
declare module 'logtown/es5/umd/plugins/stacktrace.js' {
  declare module.exports: $Exports<'logtown/es5/umd/plugins/stacktrace'>;
}
declare module 'logtown/es6/common/index.js' {
  declare module.exports: $Exports<'logtown/es6/common/index'>;
}
declare module 'logtown/es6/common/plugins/stacktrace.js' {
  declare module.exports: $Exports<'logtown/es6/common/plugins/stacktrace'>;
}
declare module 'logtown/index' {
  declare module.exports: $Exports<'logtown'>;
}
declare module 'logtown/index.js' {
  declare module.exports: $Exports<'logtown'>;
}
declare module 'logtown/plugins/stacktrace.js' {
  declare module.exports: $Exports<'logtown/plugins/stacktrace'>;
}
declare module 'logtown/rollup.config.browser.es5.js' {
  declare module.exports: $Exports<'logtown/rollup.config.browser.es5'>;
}
declare module 'logtown/rollup.config.cjs.es5.js' {
  declare module.exports: $Exports<'logtown/rollup.config.cjs.es5'>;
}
declare module 'logtown/rollup.config.cjs.es6.js' {
  declare module.exports: $Exports<'logtown/rollup.config.cjs.es6'>;
}
declare module 'logtown/utils/color.js' {
  declare module.exports: $Exports<'logtown/utils/color'>;
}
declare module 'logtown/wrappers/console.js' {
  declare module.exports: $Exports<'logtown/wrappers/console'>;
}
declare module 'logtown/wrappers/node.js' {
  declare module.exports: $Exports<'logtown/wrappers/node'>;
}
