// flow-typed signature: 517b0d39d6a88ba2ed4805f48ab8f325
// flow-typed version: <<STUB>>/logtown-winston_v^1.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'logtown-winston'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'logtown-winston' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'logtown-winston/es5/index' {
  declare module.exports: any;
}

declare module 'logtown-winston/rollup.config.cjs.es5' {
  declare module.exports: any;
}

// Filename aliases
declare module 'logtown-winston/es5/index.js' {
  declare module.exports: $Exports<'logtown-winston/es5/index'>;
}
declare module 'logtown-winston/index' {
  declare module.exports: $Exports<'logtown-winston'>;
}
declare module 'logtown-winston/index.js' {
  declare module.exports: $Exports<'logtown-winston'>;
}
declare module 'logtown-winston/rollup.config.cjs.es5.js' {
  declare module.exports: $Exports<'logtown-winston/rollup.config.cjs.es5'>;
}
