// flow-typed signature: 8664fa19465c8105af21aa9792e16801
// flow-typed version: <<STUB>>/natural_v^0.5.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'natural'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'natural' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'natural/lib/natural/analyzers/sentence_analyzer' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Tagger' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Tester' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Trainer' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/brill_pos_tagger/lib/Corpus' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/brill_pos_tagger/lib/Lexicon' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/brill_pos_tagger/lib/Predicate' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/brill_pos_tagger/lib/RuleSet' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/brill_pos_tagger/lib/RuleTemplate' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/brill_pos_tagger/lib/RuleTemplates' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/brill_pos_tagger/lib/TF_Parser' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/brill_pos_tagger/lib/TransformationRule' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/classifiers/bayes_classifier' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/classifiers/classifier' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/classifiers/logistic_regression_classifier' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/distance/dice_coefficient' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/distance/jaro-winkler_distance' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/distance/levenshtein_distance' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/index' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/inflectors/count_inflector' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/inflectors/form_set' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/inflectors/fr/count_inflector' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/inflectors/fr/noun_inflector' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/inflectors/ja/noun_inflector' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/inflectors/noun_inflector' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/inflectors/present_verb_inflector' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/inflectors/singular_plural_inflector' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/ngrams/ngrams_zh' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/ngrams/ngrams' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/normalizers/normalizer_ja' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/normalizers/normalizer_no' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/normalizers/normalizer_sv' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/normalizers/normalizer' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/normalizers/remove_diacritics' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/phonetics/dm_soundex' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/phonetics/double_metaphone' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/phonetics/metaphone' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/phonetics/phonetic' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/phonetics/soundex' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/spellcheck/spellcheck' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/indonesian/base_stemmer_id' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/indonesian/prefix_rules' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/indonesian/removal' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/indonesian/stemmer_id' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/indonesian/suffix_rules' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/lancaster_rules' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/lancaster_stemmer' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/porter_stemmer_es' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/porter_stemmer_fa' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/porter_stemmer_fr' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/porter_stemmer_it' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/porter_stemmer_no' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/porter_stemmer_pt' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/porter_stemmer_ru' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/porter_stemmer_sv' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/porter_stemmer' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/stemmer_es' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/stemmer_fa' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/stemmer_fr' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/stemmer_it' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/stemmer_ja' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/stemmer_no' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/stemmer_pl' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/stemmer_pt' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/stemmer_ru' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/stemmer_sv' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/stemmer' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/stemmers/token' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/tfidf/tfidf' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_es' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_fa' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_fr' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_id' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_it' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_nl' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_no' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_pl' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_pt' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_ru' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_sv' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/tokenizers/regexp_tokenizer' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/tokenizers/sentence_tokenizer' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/tokenizers/tokenizer_case' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/tokenizers/tokenizer_ja' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/tokenizers/tokenizer' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/tokenizers/treebank_word_tokenizer' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/transliterators/ja/index' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/trie/trie' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/util/bag' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/util/edge_weighted_digraph' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/util/longest_path_tree' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/util/shortest_path_tree' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/util/stopwords_es' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/util/stopwords_fa' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/util/stopwords_fr' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/util/stopwords_id' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/util/stopwords_it' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/util/stopwords_ja' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/util/stopwords_nl' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/util/stopwords_no' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/util/stopwords_pl' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/util/stopwords_pt' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/util/stopwords_ru' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/util/stopwords_sv' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/util/stopwords_zh' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/util/stopwords' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/util/topological' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/util/utils' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/wordnet/data_file' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/wordnet/index_file' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/wordnet/wordnet_file' {
  declare module.exports: any;
}

declare module 'natural/lib/natural/wordnet/wordnet' {
  declare module.exports: any;
}

declare module 'natural/tests/stemmer_id_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'natural/index' {
  declare module.exports: $Exports<'natural'>;
}
declare module 'natural/index.js' {
  declare module.exports: $Exports<'natural'>;
}
declare module 'natural/lib/natural/analyzers/sentence_analyzer.js' {
  declare module.exports: $Exports<'natural/lib/natural/analyzers/sentence_analyzer'>;
}
declare module 'natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Tagger.js' {
  declare module.exports: $Exports<'natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Tagger'>;
}
declare module 'natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Tester.js' {
  declare module.exports: $Exports<'natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Tester'>;
}
declare module 'natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Trainer.js' {
  declare module.exports: $Exports<'natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Trainer'>;
}
declare module 'natural/lib/natural/brill_pos_tagger/lib/Corpus.js' {
  declare module.exports: $Exports<'natural/lib/natural/brill_pos_tagger/lib/Corpus'>;
}
declare module 'natural/lib/natural/brill_pos_tagger/lib/Lexicon.js' {
  declare module.exports: $Exports<'natural/lib/natural/brill_pos_tagger/lib/Lexicon'>;
}
declare module 'natural/lib/natural/brill_pos_tagger/lib/Predicate.js' {
  declare module.exports: $Exports<'natural/lib/natural/brill_pos_tagger/lib/Predicate'>;
}
declare module 'natural/lib/natural/brill_pos_tagger/lib/RuleSet.js' {
  declare module.exports: $Exports<'natural/lib/natural/brill_pos_tagger/lib/RuleSet'>;
}
declare module 'natural/lib/natural/brill_pos_tagger/lib/RuleTemplate.js' {
  declare module.exports: $Exports<'natural/lib/natural/brill_pos_tagger/lib/RuleTemplate'>;
}
declare module 'natural/lib/natural/brill_pos_tagger/lib/RuleTemplates.js' {
  declare module.exports: $Exports<'natural/lib/natural/brill_pos_tagger/lib/RuleTemplates'>;
}
declare module 'natural/lib/natural/brill_pos_tagger/lib/TF_Parser.js' {
  declare module.exports: $Exports<'natural/lib/natural/brill_pos_tagger/lib/TF_Parser'>;
}
declare module 'natural/lib/natural/brill_pos_tagger/lib/TransformationRule.js' {
  declare module.exports: $Exports<'natural/lib/natural/brill_pos_tagger/lib/TransformationRule'>;
}
declare module 'natural/lib/natural/classifiers/bayes_classifier.js' {
  declare module.exports: $Exports<'natural/lib/natural/classifiers/bayes_classifier'>;
}
declare module 'natural/lib/natural/classifiers/classifier.js' {
  declare module.exports: $Exports<'natural/lib/natural/classifiers/classifier'>;
}
declare module 'natural/lib/natural/classifiers/logistic_regression_classifier.js' {
  declare module.exports: $Exports<
    'natural/lib/natural/classifiers/logistic_regression_classifier'
  >;
}
declare module 'natural/lib/natural/distance/dice_coefficient.js' {
  declare module.exports: $Exports<'natural/lib/natural/distance/dice_coefficient'>;
}
declare module 'natural/lib/natural/distance/jaro-winkler_distance.js' {
  declare module.exports: $Exports<'natural/lib/natural/distance/jaro-winkler_distance'>;
}
declare module 'natural/lib/natural/distance/levenshtein_distance.js' {
  declare module.exports: $Exports<'natural/lib/natural/distance/levenshtein_distance'>;
}
declare module 'natural/lib/natural/index.js' {
  declare module.exports: $Exports<'natural/lib/natural/index'>;
}
declare module 'natural/lib/natural/inflectors/count_inflector.js' {
  declare module.exports: $Exports<'natural/lib/natural/inflectors/count_inflector'>;
}
declare module 'natural/lib/natural/inflectors/form_set.js' {
  declare module.exports: $Exports<'natural/lib/natural/inflectors/form_set'>;
}
declare module 'natural/lib/natural/inflectors/fr/count_inflector.js' {
  declare module.exports: $Exports<'natural/lib/natural/inflectors/fr/count_inflector'>;
}
declare module 'natural/lib/natural/inflectors/fr/noun_inflector.js' {
  declare module.exports: $Exports<'natural/lib/natural/inflectors/fr/noun_inflector'>;
}
declare module 'natural/lib/natural/inflectors/ja/noun_inflector.js' {
  declare module.exports: $Exports<'natural/lib/natural/inflectors/ja/noun_inflector'>;
}
declare module 'natural/lib/natural/inflectors/noun_inflector.js' {
  declare module.exports: $Exports<'natural/lib/natural/inflectors/noun_inflector'>;
}
declare module 'natural/lib/natural/inflectors/present_verb_inflector.js' {
  declare module.exports: $Exports<'natural/lib/natural/inflectors/present_verb_inflector'>;
}
declare module 'natural/lib/natural/inflectors/singular_plural_inflector.js' {
  declare module.exports: $Exports<'natural/lib/natural/inflectors/singular_plural_inflector'>;
}
declare module 'natural/lib/natural/ngrams/ngrams_zh.js' {
  declare module.exports: $Exports<'natural/lib/natural/ngrams/ngrams_zh'>;
}
declare module 'natural/lib/natural/ngrams/ngrams.js' {
  declare module.exports: $Exports<'natural/lib/natural/ngrams/ngrams'>;
}
declare module 'natural/lib/natural/normalizers/normalizer_ja.js' {
  declare module.exports: $Exports<'natural/lib/natural/normalizers/normalizer_ja'>;
}
declare module 'natural/lib/natural/normalizers/normalizer_no.js' {
  declare module.exports: $Exports<'natural/lib/natural/normalizers/normalizer_no'>;
}
declare module 'natural/lib/natural/normalizers/normalizer_sv.js' {
  declare module.exports: $Exports<'natural/lib/natural/normalizers/normalizer_sv'>;
}
declare module 'natural/lib/natural/normalizers/normalizer.js' {
  declare module.exports: $Exports<'natural/lib/natural/normalizers/normalizer'>;
}
declare module 'natural/lib/natural/normalizers/remove_diacritics.js' {
  declare module.exports: $Exports<'natural/lib/natural/normalizers/remove_diacritics'>;
}
declare module 'natural/lib/natural/phonetics/dm_soundex.js' {
  declare module.exports: $Exports<'natural/lib/natural/phonetics/dm_soundex'>;
}
declare module 'natural/lib/natural/phonetics/double_metaphone.js' {
  declare module.exports: $Exports<'natural/lib/natural/phonetics/double_metaphone'>;
}
declare module 'natural/lib/natural/phonetics/metaphone.js' {
  declare module.exports: $Exports<'natural/lib/natural/phonetics/metaphone'>;
}
declare module 'natural/lib/natural/phonetics/phonetic.js' {
  declare module.exports: $Exports<'natural/lib/natural/phonetics/phonetic'>;
}
declare module 'natural/lib/natural/phonetics/soundex.js' {
  declare module.exports: $Exports<'natural/lib/natural/phonetics/soundex'>;
}
declare module 'natural/lib/natural/spellcheck/spellcheck.js' {
  declare module.exports: $Exports<'natural/lib/natural/spellcheck/spellcheck'>;
}
declare module 'natural/lib/natural/stemmers/indonesian/base_stemmer_id.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/indonesian/base_stemmer_id'>;
}
declare module 'natural/lib/natural/stemmers/indonesian/prefix_rules.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/indonesian/prefix_rules'>;
}
declare module 'natural/lib/natural/stemmers/indonesian/removal.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/indonesian/removal'>;
}
declare module 'natural/lib/natural/stemmers/indonesian/stemmer_id.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/indonesian/stemmer_id'>;
}
declare module 'natural/lib/natural/stemmers/indonesian/suffix_rules.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/indonesian/suffix_rules'>;
}
declare module 'natural/lib/natural/stemmers/lancaster_rules.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/lancaster_rules'>;
}
declare module 'natural/lib/natural/stemmers/lancaster_stemmer.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/lancaster_stemmer'>;
}
declare module 'natural/lib/natural/stemmers/porter_stemmer_es.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/porter_stemmer_es'>;
}
declare module 'natural/lib/natural/stemmers/porter_stemmer_fa.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/porter_stemmer_fa'>;
}
declare module 'natural/lib/natural/stemmers/porter_stemmer_fr.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/porter_stemmer_fr'>;
}
declare module 'natural/lib/natural/stemmers/porter_stemmer_it.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/porter_stemmer_it'>;
}
declare module 'natural/lib/natural/stemmers/porter_stemmer_no.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/porter_stemmer_no'>;
}
declare module 'natural/lib/natural/stemmers/porter_stemmer_pt.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/porter_stemmer_pt'>;
}
declare module 'natural/lib/natural/stemmers/porter_stemmer_ru.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/porter_stemmer_ru'>;
}
declare module 'natural/lib/natural/stemmers/porter_stemmer_sv.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/porter_stemmer_sv'>;
}
declare module 'natural/lib/natural/stemmers/porter_stemmer.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/porter_stemmer'>;
}
declare module 'natural/lib/natural/stemmers/stemmer_es.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/stemmer_es'>;
}
declare module 'natural/lib/natural/stemmers/stemmer_fa.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/stemmer_fa'>;
}
declare module 'natural/lib/natural/stemmers/stemmer_fr.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/stemmer_fr'>;
}
declare module 'natural/lib/natural/stemmers/stemmer_it.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/stemmer_it'>;
}
declare module 'natural/lib/natural/stemmers/stemmer_ja.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/stemmer_ja'>;
}
declare module 'natural/lib/natural/stemmers/stemmer_no.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/stemmer_no'>;
}
declare module 'natural/lib/natural/stemmers/stemmer_pl.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/stemmer_pl'>;
}
declare module 'natural/lib/natural/stemmers/stemmer_pt.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/stemmer_pt'>;
}
declare module 'natural/lib/natural/stemmers/stemmer_ru.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/stemmer_ru'>;
}
declare module 'natural/lib/natural/stemmers/stemmer_sv.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/stemmer_sv'>;
}
declare module 'natural/lib/natural/stemmers/stemmer.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/stemmer'>;
}
declare module 'natural/lib/natural/stemmers/token.js' {
  declare module.exports: $Exports<'natural/lib/natural/stemmers/token'>;
}
declare module 'natural/lib/natural/tfidf/tfidf.js' {
  declare module.exports: $Exports<'natural/lib/natural/tfidf/tfidf'>;
}
declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_es.js' {
  declare module.exports: $Exports<'natural/lib/natural/tokenizers/aggressive_tokenizer_es'>;
}
declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_fa.js' {
  declare module.exports: $Exports<'natural/lib/natural/tokenizers/aggressive_tokenizer_fa'>;
}
declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_fr.js' {
  declare module.exports: $Exports<'natural/lib/natural/tokenizers/aggressive_tokenizer_fr'>;
}
declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_id.js' {
  declare module.exports: $Exports<'natural/lib/natural/tokenizers/aggressive_tokenizer_id'>;
}
declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_it.js' {
  declare module.exports: $Exports<'natural/lib/natural/tokenizers/aggressive_tokenizer_it'>;
}
declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_nl.js' {
  declare module.exports: $Exports<'natural/lib/natural/tokenizers/aggressive_tokenizer_nl'>;
}
declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_no.js' {
  declare module.exports: $Exports<'natural/lib/natural/tokenizers/aggressive_tokenizer_no'>;
}
declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_pl.js' {
  declare module.exports: $Exports<'natural/lib/natural/tokenizers/aggressive_tokenizer_pl'>;
}
declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_pt.js' {
  declare module.exports: $Exports<'natural/lib/natural/tokenizers/aggressive_tokenizer_pt'>;
}
declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_ru.js' {
  declare module.exports: $Exports<'natural/lib/natural/tokenizers/aggressive_tokenizer_ru'>;
}
declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer_sv.js' {
  declare module.exports: $Exports<'natural/lib/natural/tokenizers/aggressive_tokenizer_sv'>;
}
declare module 'natural/lib/natural/tokenizers/aggressive_tokenizer.js' {
  declare module.exports: $Exports<'natural/lib/natural/tokenizers/aggressive_tokenizer'>;
}
declare module 'natural/lib/natural/tokenizers/regexp_tokenizer.js' {
  declare module.exports: $Exports<'natural/lib/natural/tokenizers/regexp_tokenizer'>;
}
declare module 'natural/lib/natural/tokenizers/sentence_tokenizer.js' {
  declare module.exports: $Exports<'natural/lib/natural/tokenizers/sentence_tokenizer'>;
}
declare module 'natural/lib/natural/tokenizers/tokenizer_case.js' {
  declare module.exports: $Exports<'natural/lib/natural/tokenizers/tokenizer_case'>;
}
declare module 'natural/lib/natural/tokenizers/tokenizer_ja.js' {
  declare module.exports: $Exports<'natural/lib/natural/tokenizers/tokenizer_ja'>;
}
declare module 'natural/lib/natural/tokenizers/tokenizer.js' {
  declare module.exports: $Exports<'natural/lib/natural/tokenizers/tokenizer'>;
}
declare module 'natural/lib/natural/tokenizers/treebank_word_tokenizer.js' {
  declare module.exports: $Exports<'natural/lib/natural/tokenizers/treebank_word_tokenizer'>;
}
declare module 'natural/lib/natural/transliterators/ja/index.js' {
  declare module.exports: $Exports<'natural/lib/natural/transliterators/ja/index'>;
}
declare module 'natural/lib/natural/trie/trie.js' {
  declare module.exports: $Exports<'natural/lib/natural/trie/trie'>;
}
declare module 'natural/lib/natural/util/bag.js' {
  declare module.exports: $Exports<'natural/lib/natural/util/bag'>;
}
declare module 'natural/lib/natural/util/edge_weighted_digraph.js' {
  declare module.exports: $Exports<'natural/lib/natural/util/edge_weighted_digraph'>;
}
declare module 'natural/lib/natural/util/longest_path_tree.js' {
  declare module.exports: $Exports<'natural/lib/natural/util/longest_path_tree'>;
}
declare module 'natural/lib/natural/util/shortest_path_tree.js' {
  declare module.exports: $Exports<'natural/lib/natural/util/shortest_path_tree'>;
}
declare module 'natural/lib/natural/util/stopwords_es.js' {
  declare module.exports: $Exports<'natural/lib/natural/util/stopwords_es'>;
}
declare module 'natural/lib/natural/util/stopwords_fa.js' {
  declare module.exports: $Exports<'natural/lib/natural/util/stopwords_fa'>;
}
declare module 'natural/lib/natural/util/stopwords_fr.js' {
  declare module.exports: $Exports<'natural/lib/natural/util/stopwords_fr'>;
}
declare module 'natural/lib/natural/util/stopwords_id.js' {
  declare module.exports: $Exports<'natural/lib/natural/util/stopwords_id'>;
}
declare module 'natural/lib/natural/util/stopwords_it.js' {
  declare module.exports: $Exports<'natural/lib/natural/util/stopwords_it'>;
}
declare module 'natural/lib/natural/util/stopwords_ja.js' {
  declare module.exports: $Exports<'natural/lib/natural/util/stopwords_ja'>;
}
declare module 'natural/lib/natural/util/stopwords_nl.js' {
  declare module.exports: $Exports<'natural/lib/natural/util/stopwords_nl'>;
}
declare module 'natural/lib/natural/util/stopwords_no.js' {
  declare module.exports: $Exports<'natural/lib/natural/util/stopwords_no'>;
}
declare module 'natural/lib/natural/util/stopwords_pl.js' {
  declare module.exports: $Exports<'natural/lib/natural/util/stopwords_pl'>;
}
declare module 'natural/lib/natural/util/stopwords_pt.js' {
  declare module.exports: $Exports<'natural/lib/natural/util/stopwords_pt'>;
}
declare module 'natural/lib/natural/util/stopwords_ru.js' {
  declare module.exports: $Exports<'natural/lib/natural/util/stopwords_ru'>;
}
declare module 'natural/lib/natural/util/stopwords_sv.js' {
  declare module.exports: $Exports<'natural/lib/natural/util/stopwords_sv'>;
}
declare module 'natural/lib/natural/util/stopwords_zh.js' {
  declare module.exports: $Exports<'natural/lib/natural/util/stopwords_zh'>;
}
declare module 'natural/lib/natural/util/stopwords.js' {
  declare module.exports: $Exports<'natural/lib/natural/util/stopwords'>;
}
declare module 'natural/lib/natural/util/topological.js' {
  declare module.exports: $Exports<'natural/lib/natural/util/topological'>;
}
declare module 'natural/lib/natural/util/utils.js' {
  declare module.exports: $Exports<'natural/lib/natural/util/utils'>;
}
declare module 'natural/lib/natural/wordnet/data_file.js' {
  declare module.exports: $Exports<'natural/lib/natural/wordnet/data_file'>;
}
declare module 'natural/lib/natural/wordnet/index_file.js' {
  declare module.exports: $Exports<'natural/lib/natural/wordnet/index_file'>;
}
declare module 'natural/lib/natural/wordnet/wordnet_file.js' {
  declare module.exports: $Exports<'natural/lib/natural/wordnet/wordnet_file'>;
}
declare module 'natural/lib/natural/wordnet/wordnet.js' {
  declare module.exports: $Exports<'natural/lib/natural/wordnet/wordnet'>;
}
declare module 'natural/tests/stemmer_id_test.js' {
  declare module.exports: $Exports<'natural/tests/stemmer_id_test'>;
}
