// flow-typed signature: 98232eb179260c3e56c55157eabb6723
// flow-typed version: <<STUB>>/node-dir_v^0.1.17

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-dir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-dir' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-dir/lib/paths' {
  declare module.exports: any;
}

declare module 'node-dir/lib/readfiles' {
  declare module.exports: any;
}

declare module 'node-dir/lib/readfilesstream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-dir/index' {
  declare module.exports: $Exports<'node-dir'>;
}
declare module 'node-dir/index.js' {
  declare module.exports: $Exports<'node-dir'>;
}
declare module 'node-dir/lib/paths.js' {
  declare module.exports: $Exports<'node-dir/lib/paths'>;
}
declare module 'node-dir/lib/readfiles.js' {
  declare module.exports: $Exports<'node-dir/lib/readfiles'>;
}
declare module 'node-dir/lib/readfilesstream.js' {
  declare module.exports: $Exports<'node-dir/lib/readfilesstream'>;
}
