// flow-typed signature: 21202c0cc14d3e43e2470e5c3863388e
// flow-typed version: <<STUB>>/replay_v^2.1.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'replay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'replay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'replay/example/test' {
  declare module.exports: any;
}

declare module 'replay/Gulpfile' {
  declare module.exports: any;
}

declare module 'replay/lib/catalog' {
  declare module.exports: any;
}

declare module 'replay/lib/chain' {
  declare module.exports: any;
}

declare module 'replay/lib/debug' {
  declare module.exports: any;
}

declare module 'replay/lib/index' {
  declare module.exports: any;
}

declare module 'replay/lib/logger' {
  declare module.exports: any;
}

declare module 'replay/lib/matcher' {
  declare module.exports: any;
}

declare module 'replay/lib/pass_through' {
  declare module.exports: any;
}

declare module 'replay/lib/patch_dns_lookup' {
  declare module.exports: any;
}

declare module 'replay/lib/patch_http_request' {
  declare module.exports: any;
}

declare module 'replay/lib/proxy' {
  declare module.exports: any;
}

declare module 'replay/lib/recorder' {
  declare module.exports: any;
}

declare module 'replay/test/helpers' {
  declare module.exports: any;
}

declare module 'replay/test/pass_through_test' {
  declare module.exports: any;
}

declare module 'replay/test/replay_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'replay/example/test.js' {
  declare module.exports: $Exports<'replay/example/test'>;
}
declare module 'replay/Gulpfile.js' {
  declare module.exports: $Exports<'replay/Gulpfile'>;
}
declare module 'replay/lib/catalog.js' {
  declare module.exports: $Exports<'replay/lib/catalog'>;
}
declare module 'replay/lib/chain.js' {
  declare module.exports: $Exports<'replay/lib/chain'>;
}
declare module 'replay/lib/debug.js' {
  declare module.exports: $Exports<'replay/lib/debug'>;
}
declare module 'replay/lib/index.js' {
  declare module.exports: $Exports<'replay/lib/index'>;
}
declare module 'replay/lib/logger.js' {
  declare module.exports: $Exports<'replay/lib/logger'>;
}
declare module 'replay/lib/matcher.js' {
  declare module.exports: $Exports<'replay/lib/matcher'>;
}
declare module 'replay/lib/pass_through.js' {
  declare module.exports: $Exports<'replay/lib/pass_through'>;
}
declare module 'replay/lib/patch_dns_lookup.js' {
  declare module.exports: $Exports<'replay/lib/patch_dns_lookup'>;
}
declare module 'replay/lib/patch_http_request.js' {
  declare module.exports: $Exports<'replay/lib/patch_http_request'>;
}
declare module 'replay/lib/proxy.js' {
  declare module.exports: $Exports<'replay/lib/proxy'>;
}
declare module 'replay/lib/recorder.js' {
  declare module.exports: $Exports<'replay/lib/recorder'>;
}
declare module 'replay/test/helpers.js' {
  declare module.exports: $Exports<'replay/test/helpers'>;
}
declare module 'replay/test/pass_through_test.js' {
  declare module.exports: $Exports<'replay/test/pass_through_test'>;
}
declare module 'replay/test/replay_test.js' {
  declare module.exports: $Exports<'replay/test/replay_test'>;
}
